// ==== KHO DỮ LIỆU — sửa file này để thêm từ vựng dần ====
// Mỗi mục: {c:"category", l:"中級|上級", jp:"表現", y:"đọc kana", vi:"nghĩa", ex:"ví dụ", n:"lưu ý (tùy chọn)"}

window.VOCAB_CATS = {
  conclusion:{jp:"結論・要約", vi:"Kết luận"},
  organize:  {jp:"論点整理",   vi:"Sắp xếp ý"},
  cushion:   {jp:"クッション", vi:"Rào đón"},
  opinion:   {jp:"意見・提案", vi:"Ý kiến"},
  request:   {jp:"依頼・催促", vi:"Nhờ·Nhắc"},
  decline:   {jp:"断り・お詫び",vi:"Từ chối·Xin lỗi"},
  transition:{jp:"転換・つなぎ",vi:"Chuyển ý"},
  emphasis:  {jp:"強調",       vi:"Nhấn mạnh"},
  jargon:    {jp:"業務慣用句", vi:"Jargon nội bộ"},
  consult:   {jp:"コンサル語彙",vi:"Consultant"},
  yoji:      {jp:"四字熟語",   vi:"Thành ngữ 4 chữ"},
  proverb:   {jp:"ことわざ",   vi:"Tục ngữ"},
  greeting:  {jp:"挨拶・書き出し",vi:"Mở đầu mail"},
  closing:   {jp:"結び",        vi:"Kết mail"},
  gratitude: {jp:"感謝・お礼",  vi:"Cảm ơn"},
  confirm:   {jp:"確認・合意",  vi:"Xác nhận"},
  report:    {jp:"報告・状況",  vi:"Báo cáo"},
  facilitation:{jp:"会議進行・相槌",vi:"Điều phối họp"},
  keigo:     {jp:"敬語語彙",    vi:"Kính ngữ"},
};

window.VOCAB_DATA = [
  // 1. 結論・要約
  {c:"conclusion",l:"中級",jp:"結論から申し上げますと",y:"けつろんからもうしあげますと",vi:"Nói kết luận trước (PREP)",ex:"結論から申し上げますと、本機能は次フェーズでの対応を推奨します。",n:"Cụm đáng thuộc nhất — hợp lối báo cáo kết-luận-trước mà sếp Nhật thích."},
  {c:"conclusion",l:"中級",jp:"掻い摘んで申し上げますと",y:"かいつまんでもうしあげますと",vi:"Tóm những điểm cốt lõi",ex:"掻い摘んで申し上げますと、遅延の主因は要件確定の遅れです。"},
  {c:"conclusion",l:"中級",jp:"端的に申し上げると",y:"たんてきにもうしあげると",vi:"Nói thẳng, gọn",ex:"端的に申し上げると、現行案ではコストが2割超過します。"},
  {c:"conclusion",l:"中級",jp:"要点を絞って申し上げると",y:"ようてんをしぼってもうしあげると",vi:"Thu hẹp vào điểm chính",ex:"要点を絞って申し上げると、論点は2つです。"},

  // 2. 論点整理
  {c:"organize",l:"中級",jp:"論点を整理いたしますと",y:"ろんてんをせいりいたしますと",vi:"Sắp xếp lại các điểm",ex:"論点を整理いたしますと、課題は「コスト」「納期」「品質」の3点です。"},
  {c:"organize",l:"上級",jp:"大別すると",y:"たいべつすると",vi:"Chia lớn thành",ex:"大別すると、対応策は二つに分かれます。"},
  {c:"organize",l:"上級",jp:"突き詰めますと",y:"つきつめますと",vi:"Truy đến cùng / nói cho cùng",ex:"突き詰めますと、根本原因は体制側にあります。",n:"Nghe sắc — với khách nhạy cảm thì giảm liều."},
  {c:"organize",l:"中級",jp:"順を追って説明しますと",y:"じゅんをおってせつめいしますと",vi:"Giải thích theo trình tự",ex:"順を追って説明しますと、まず背景からお話しします。"},

  // 3. クッション
  {c:"cushion",l:"上級",jp:"僭越ながら",y:"せんえつながら",vi:"Dù có phần vượt phận…",ex:"僭越ながら、一点だけ確認させていただけますでしょうか。",n:"Sắc thái khiêm tốn mạnh — dùng với cấp trên/khách, không dùng với cấp dưới."},
  {c:"cushion",l:"中級",jp:"差し支えなければ",y:"さしつかえなければ",vi:"Nếu không bất tiện",ex:"差し支えなければ、背景を伺ってもよろしいでしょうか。"},
  {c:"cushion",l:"上級",jp:"お言葉を返すようですが",y:"おことばをかえすようですが",vi:"Xin phép phản hồi lại (bất đồng lịch sự)",ex:"お言葉を返すようですが、その前提には懸念がございます。"},
  {c:"cushion",l:"上級",jp:"釈迦に説法かもしれませんが",y:"しゃかにせっぽうかもしれませんが",vi:"Múa rìu qua mắt thợ",ex:"釈迦に説法かもしれませんが、念のため共有いたします。",n:"Dùng sai (mỉa mai / với người dưới) sẽ phản tác dụng."},
  {c:"cushion",l:"中級",jp:"ご承知のことと存じますが",y:"ごしょうちのこととぞんじますが",vi:"Như quý vị đã biết",ex:"ご承知のことと存じますが、念のため確認いたします。"},

  // 4. 意見・提案
  {c:"opinion",l:"中級",jp:"私見ではございますが",y:"しけんではございますが",vi:"Theo ý kiến cá nhân",ex:"私見ではございますが、A案のほうが拡張性が高いと考えます。"},
  {c:"opinion",l:"中級",jp:"あくまで一案ですが",y:"あくまでいちあんですが",vi:"Chỉ là một phương án thôi",ex:"あくまで一案ですが、段階的な導入も選択肢かと存じます。"},
  {c:"opinion",l:"上級",jp:"一概には申し上げられませんが",y:"いちがいにはもうしあげられませんが",vi:"Không thể nói chung chung, nhưng",ex:"一概には申し上げられませんが、傾向としてはBが優勢です。"},
  {c:"opinion",l:"中級",jp:"〜してはいかがでしょうか",y:"〜してはいかがでしょうか",vi:"Đề xuất khéo: \"hay là…\"",ex:"まず小規模で試してはいかがでしょうか。"},

  // 5. 依頼・催促
  {c:"request",l:"中級",jp:"お力添えいただけますと幸いです",y:"おちからぞえいただけますとさいわいです",vi:"Rất mong nhận được sự hỗ trợ",ex:"ご多忙のところ恐縮ですが、お力添えいただけますと幸いです。"},
  {c:"request",l:"中級",jp:"折り入ってお願いがございます",y:"おりいっておねがいがございます",vi:"Có việc muốn nhờ riêng (báo hiệu quan trọng)",ex:"折り入ってお願いがございます。お時間よろしいでしょうか。"},
  {c:"request",l:"中級",jp:"お手数をおかけしますが",y:"おてすうをおかけしますが",vi:"Phiền anh/chị, nhưng… (đệm trước khi nhờ)",ex:"お手数をおかけしますが、ご確認をお願いいたします。"},
  {c:"request",l:"中級",jp:"ご多忙のところ恐縮ですが",y:"ごたぼうのところきょうしゅくですが",vi:"Xin lỗi đã làm phiền lúc bận",ex:"ご多忙のところ恐縮ですが、ご返信をお待ちしております。"},
  {c:"request",l:"中級",jp:"度々恐れ入りますが",y:"たびたびおそれいりますが",vi:"Xin lỗi vì lại làm phiền (nhắc lần 2+)",ex:"度々恐れ入りますが、進捗はいかがでしょうか。"},

  // 6. 断り・お詫び
  {c:"decline",l:"中級",jp:"一度持ち帰らせてください",y:"いちどもちかえらせてください",vi:"Cho tôi mang về (xem xét/bàn nội bộ)",ex:"一度持ち帰らせてください。社内で検討いたします。",n:"Câu vàng để không chốt vội."},
  {c:"decline",l:"上級",jp:"心苦しいのですが",y:"こころぐるしいのですが",vi:"Thật lòng áy náy, nhưng… (đệm từ chối)",ex:"心苦しいのですが、今回は見送らせていただきます。"},
  {c:"decline",l:"中級",jp:"今回は見送らせていただきます",y:"こんかいはみおくらせていただきます",vi:"Lần này xin phép bỏ qua",ex:"検討の結果、今回は見送らせていただきます。"},
  {c:"decline",l:"中級",jp:"ご迷惑をおかけし申し訳ございません",y:"ごめいわくをおかけしもうしわけございません",vi:"Xin lỗi vì đã gây phiền toái",ex:"この度はご迷惑をおかけし申し訳ございません。"},
  {c:"decline",l:"上級",jp:"弁解の余地もございません",y:"べんかいのよちもございません",vi:"Không có gì để biện minh (xin lỗi nặng)",ex:"私の確認不足であり、弁解の余地もございません。"},
  {c:"decline",l:"中級",jp:"以後、十分注意いたします",y:"いご、じゅうぶんちゅういいたします",vi:"Từ nay tôi sẽ hết sức chú ý",ex:"以後、十分注意いたします。"},

  // 7. 転換・つなぎ
  {c:"transition",l:"中級",jp:"それを踏まえまして",y:"それをふまえまして",vi:"Dựa trên điều đó",ex:"それを踏まえまして、次のステップをご提案します。"},
  {c:"transition",l:"中級",jp:"これを受けまして",y:"これをうけまして",vi:"Đáp lại điều này",ex:"これを受けまして、方針を見直します。"},
  {c:"transition",l:"上級",jp:"翻って",y:"ひるがえって",vi:"Quay lại / mặt khác",ex:"翻って、コスト面ではどうでしょうか。"},
  {c:"transition",l:"上級",jp:"裏を返せば",y:"うらをかえせば",vi:"Nói ngược lại thì",ex:"裏を返せば、ここが最大の差別化要因です。"},

  // 8. 強調
  {c:"emphasis",l:"中級",jp:"とりわけ",y:"とりわけ",vi:"Đặc biệt là",ex:"とりわけ、セキュリティ要件は最優先です。"},
  {c:"emphasis",l:"上級",jp:"殊に",y:"ことに",vi:"Nhất là (trang trọng)",ex:"殊に、初期設定の工数が大きく膨らみます。"},
  {c:"emphasis",l:"中級",jp:"言うまでもなく",y:"いうまでもなく",vi:"Khỏi phải nói",ex:"言うまでもなく、データ移行が最大の山場です。"},
  {c:"emphasis",l:"上級",jp:"何にも増して",y:"なににもまして",vi:"Hơn bất cứ điều gì",ex:"何にも増して、品質を優先します。"},

  // 9. 業務慣用句
  {c:"jargon",l:"中級",jp:"握る",y:"にぎる",vi:"Chốt/thống nhất ngầm với một bên trước",ex:"事前に先方と握っておきます。",n:"Ngôn ngữ nội bộ — không dùng trong văn bản trang trọng gửi khách."},
  {c:"jargon",l:"中級",jp:"詰める",y:"つめる",vi:"Đào sâu chi tiết đến khi rõ",ex:"仕様を詰めましょう。"},
  {c:"jargon",l:"中級",jp:"巻き取る",y:"まきとる",vi:"Ôm việc của bên khác về mình xử lý",ex:"その作業はこちらで巻き取ります。"},
  {c:"jargon",l:"中級",jp:"ボールを持つ",y:"ボールをもつ",vi:"Đang là người phải xử lý tiếp",ex:"今ボールはこちらにあります。"},
  {c:"jargon",l:"中級",jp:"落とし所",y:"おとしどころ",vi:"Điểm thỏa hiệp hai bên chấp nhận được",ex:"落とし所を探りましょう。"},
  {c:"jargon",l:"中級",jp:"温度感",y:"おんどかん",vi:"Mức độ sốt sắng/ưu tiên của các bên",ex:"先方の温度感を確認したいです。",hv:"ôn độ cảm"},
  {c:"jargon",l:"中級",jp:"腹落ち",y:"はらおち",vi:"Hiểu và thấm thật sự, tâm phục",ex:"メンバーがまだ腹落ちしていません。"},
  {c:"jargon",l:"中級",jp:"棚卸し",y:"たなおろし",vi:"Rà soát / kiểm kê lại toàn bộ",ex:"一度、課題を棚卸ししましょう。"},
  {c:"jargon",l:"中級",jp:"地ならし",y:"じならし",vi:"Dọn đường trước (≈ 根回し)",ex:"役員への地ならしが必要です。"},
  {c:"jargon",l:"中級",jp:"刺さる",y:"ささる",vi:"\"Trúng\" đúng nhu cầu đối phương",ex:"この提案は刺さると思います。"},
  {c:"jargon",l:"中級",jp:"寝かせる",y:"ねかせる",vi:"Tạm để đó, chưa động (cho chín)",ex:"この案は一旦寝かせましょう。"},

  // 10. コンサル語彙
  {c:"consult",l:"上級",jp:"解像度を上げる",y:"かいぞうどをあげる",vi:"Làm rõ / chi tiết hóa nhận thức",ex:"課題の解像度を上げましょう。",n:"Tầng dễ thành khoe chữ — chỉ dùng khi nó làm câu nói CHÍNH XÁC hơn.",hv:"giải tượng độ"},
  {c:"consult",l:"上級",jp:"粒度",y:"りゅうど",vi:"Độ mịn / mức chi tiết (granularity)",ex:"タスクの粒度を揃えましょう。",hv:"lạp độ"},
  {c:"consult",l:"上級",jp:"与件",y:"よけん",vi:"Điều kiện/tiền đề đã cho, không bàn cãi",ex:"これは与件として進めます。",hv:"dữ kiện"},
  {c:"consult",l:"上級",jp:"建て付け",y:"たてつけ",vi:"Cách một đề án/tổ chức được \"dựng\" (cơ chế)",ex:"この企画の建て付けを見直したいです。"},
  {c:"consult",l:"上級",jp:"座組み",y:"ざぐみ",vi:"Cách bố trí đội ngũ & các bên tham gia",ex:"プロジェクトの座組みを固めます。"},
  {c:"consult",l:"上級",jp:"力学",y:"りきがく",vi:"Quan hệ quyền lực/động lực giữa các bên",ex:"組織の力学を考慮する必要があります。",hv:"lực học"},
  {c:"consult",l:"上級",jp:"蓋然性",y:"がいぜんせい",vi:"Xác suất / khả năng xảy ra (trang trọng)",ex:"成功の蓋然性は高いと見ています。",hv:"cái nhiên tính"},
  {c:"consult",l:"上級",jp:"認識齟齬",y:"にんしきそご",vi:"Lệch nhận thức giữa các bên",ex:"認識齟齬を解消しましょう。",hv:"nhận thức trở ngữ"},
  {c:"consult",l:"上級",jp:"期待値調整",y:"きたいちちょうせい",vi:"Chỉnh kỳ vọng của khách/sếp để tránh hụt",ex:"事前に期待値調整をしておきます。",hv:"kỳ đãi trị điều chỉnh"},
  {c:"consult",l:"上級",jp:"言語化",y:"げんごか",vi:"Diễn đạt thành lời cái còn mơ hồ",ex:"まず課題を言語化することが第一歩です。",hv:"ngôn ngữ hóa"},
  {c:"consult",l:"上級",jp:"落とし込む",y:"おとしこむ",vi:"Cụ thể hóa ý tưởng thành việc/thực thi",ex:"戦略を具体的な施策に落とし込みます。"},
  {c:"consult",l:"上級",jp:"腹を括る",y:"はらをくくる",vi:"Quyết tâm, sẵn sàng nhận rủi ro",ex:"ここは腹を括って進めます。"},
  {c:"consult",l:"上級",jp:"筋がいい",y:"すじがいい",vi:"Hợp lý về bản chất (cách tiếp cận tốt)",ex:"この案は筋がいいと思います。"},

  // 11. 四字熟語
  {c:"yoji",l:"上級",jp:"試行錯誤",y:"しこうさくご",vi:"Thử và sai (trial & error)",ex:"試行錯誤を重ねて改善します。",hv:"thí hành thác ngộ"},
  {c:"yoji",l:"上級",jp:"臨機応変",y:"りんきおうへん",vi:"Linh hoạt theo tình huống",ex:"状況に応じて臨機応変に対応します。",hv:"lâm cơ ứng biến"},
  {c:"yoji",l:"上級",jp:"取捨選択",y:"しゅしゃせんたく",vi:"Chọn lọc giữ/bỏ",ex:"機能の取捨選択が必要です。",hv:"thủ xả tuyển trạch"},
  {c:"yoji",l:"上級",jp:"一長一短",y:"いっちょういったん",vi:"Mỗi cái có ưu/nhược",ex:"どの案も一長一短です。",hv:"nhất trường nhất đoản"},
  {c:"yoji",l:"上級",jp:"是々非々",y:"ぜぜひひ",vi:"Xét đúng-sai theo từng việc, không thiên vị",ex:"是々非々で判断します。",hv:"thị thị phi phi"},
  {c:"yoji",l:"上級",jp:"大同小異",y:"だいどうしょうい",vi:"Về cơ bản giống, khác nhỏ",ex:"各案は大同小異です。",hv:"đại đồng tiểu dị"},
  {c:"yoji",l:"上級",jp:"玉石混交",y:"ぎょくせきこんこう",vi:"Vàng thau lẫn lộn",ex:"ネット上の情報は玉石混交です。",hv:"ngọc thạch hỗn giao"},
  {c:"yoji",l:"上級",jp:"朝令暮改",y:"ちょうれいぼかい",vi:"Sáng ra lệnh chiều đổi (chê sự thiếu nhất quán)",ex:"朝令暮改は避けたいです。",hv:"triêu lệnh mộ cải"},
  {c:"yoji",l:"上級",jp:"一気呵成",y:"いっきかせい",vi:"Làm một mạch theo đà",ex:"この勢いで一気呵成に仕上げます。",hv:"nhất khí ha thành"},
  {c:"yoji",l:"上級",jp:"千載一遇",y:"せんざいいちぐう",vi:"Cơ hội ngàn năm có một",ex:"これは千載一遇のチャンスです。",hv:"thiên tải nhất ngộ"},

  // 12. ことわざ・慣用句
  {c:"proverb",l:"上級",jp:"急がば回れ",y:"いそがばまわれ",vi:"Dục tốc bất đạt, chọn đường chắc",ex:"急がば回れで、慎重に進めます。",n:"Dùng để TẢ cách mình làm thì ổn; dùng để DẠY đối phương (nhất là sếp/khách) nghe kẻ cả."},
  {c:"proverb",l:"上級",jp:"石橋を叩いて渡る",y:"いしばしをたたいてわたる",vi:"Cẩn thận tột độ",ex:"石橋を叩いて渡る進め方をします。"},
  {c:"proverb",l:"上級",jp:"餅は餅屋",y:"もちはもちや",vi:"Việc chuyên môn để chuyên gia làm",ex:"餅は餅屋で、専門家に任せましょう。"},
  {c:"proverb",l:"上級",jp:"木を見て森を見ず",y:"きをみてもりをみず",vi:"Thấy cây không thấy rừng",ex:"木を見て森を見ずにならないようにします。"},
  {c:"proverb",l:"上級",jp:"雨降って地固まる",y:"あめふってじかたまる",vi:"Sau va chạm, quan hệ vững hơn",ex:"雨降って地固まるで、今回で関係が深まりました。"},
  {c:"proverb",l:"上級",jp:"釘を刺す",y:"くぎをさす",vi:"Nhắc/cảnh báo trước để khỏi quên/sai",ex:"念のため釘を刺しておきます。"},
  {c:"proverb",l:"上級",jp:"顔を立てる",y:"かおをたてる",vi:"Giữ thể diện cho ai",ex:"部長の顔を立てる必要があります。"},
  {c:"proverb",l:"上級",jp:"筋を通す",y:"すじをとおす",vi:"Làm đúng quy trình/đạo lý",ex:"きちんと筋を通して進めます。"},
  {c:"proverb",l:"上級",jp:"後手に回る",y:"ごてにまわる",vi:"Bị động, chậm chân",ex:"対応が後手に回らないようにします。"},
  {c:"proverb",l:"上級",jp:"二の足を踏む",y:"にのあしをふむ",vi:"Chần chừ, do dự",ex:"投資に二の足を踏んでいます。"},

  // ===== BỔ SUNG nhóm cũ =====
  // 結論・要約
  {c:"conclusion",l:"中級",jp:"一言で申し上げると",y:"ひとことでもうしあげると",vi:"Nói gọn một câu",ex:"一言で申し上げると、間に合います。"},
  {c:"conclusion",l:"中級",jp:"簡潔に申し上げますと",y:"かんけつにもうしあげますと",vi:"Nói ngắn gọn",ex:"簡潔に申し上げますと、方針に変更はありません。"},
  {c:"conclusion",l:"中級",jp:"まとめますと",y:"まとめますと",vi:"Tóm lại thì",ex:"まとめますと、次回までに3点を対応します。"},
  {c:"conclusion",l:"中級",jp:"平たく言えば",y:"ひらたくいえば",vi:"Nói nôm na",ex:"平たく言えば、やり直しが必要です。"},
  // 論点整理
  {c:"organize",l:"中級",jp:"切り分けて考えますと",y:"きりわけてかんがえますと",vi:"Tách bạch ra mà xét",ex:"問題を切り分けて考えますと、原因は2系統です。"},
  {c:"organize",l:"中級",jp:"前提を確認しますと",y:"ぜんていをかくにんしますと",vi:"Xác nhận tiền đề thì",ex:"前提を確認しますと、予算は据え置きです。"},
  {c:"organize",l:"上級",jp:"構造的に申し上げると",y:"こうぞうてきにもうしあげると",vi:"Xét về mặt cấu trúc",ex:"構造的に申し上げると、上流工程に課題があります。"},
  {c:"organize",l:"上級",jp:"因数分解しますと",y:"いんすうぶんかいしますと",vi:"\"Phân tích thành nhân tố\" (chia nhỏ vấn đề)",ex:"課題を因数分解しますと、3要素に分けられます。",n:"Từ giới consultant — chỉ dùng khi thật sự đang chia nhỏ vấn đề."},
  // クッション
  {c:"cushion",l:"中級",jp:"恐れ入りますが",y:"おそれいりますが",vi:"Xin thứ lỗi nhưng… (đệm phổ biến)",ex:"恐れ入りますが、もう一度ご説明いただけますか。"},
  {c:"cushion",l:"中級",jp:"大変恐縮ですが",y:"たいへんきょうしゅくですが",vi:"Thật ngại quá nhưng…",ex:"大変恐縮ですが、締め切りの前倒しは可能でしょうか。"},
  {c:"cushion",l:"中級",jp:"申し上げにくいのですが",y:"もうしあげにくいのですが",vi:"Khó nói nhưng…",ex:"申し上げにくいのですが、品質に懸念がございます。"},
  {c:"cushion",l:"上級",jp:"立ち入ったことを伺いますが",y:"たちいったことをうかがいますが",vi:"Hỏi hơi sâu/riêng tư nhưng…",ex:"立ち入ったことを伺いますが、ご予算感はいかがでしょうか。"},
  {c:"cushion",l:"上級",jp:"ぶしつけながら",y:"ぶしつけながら",vi:"Hơi đường đột nhưng…",ex:"ぶしつけながら、率直に申し上げます。"},
  // 意見・提案
  {c:"opinion",l:"中級",jp:"〜と認識しております",y:"〜とにんしきしております",vi:"Tôi nhận thức rằng…",ex:"現時点では予定通りと認識しております。"},
  {c:"opinion",l:"中級",jp:"〜と考えております",y:"〜とかんがえております",vi:"Tôi cho rằng…",ex:"リスクは限定的と考えております。"},
  {c:"opinion",l:"上級",jp:"〜の余地があるかと存じます",y:"〜のよちがあるかとぞんじます",vi:"Có lẽ còn dư địa để…",ex:"改善の余地があるかと存じます。"},
  {c:"opinion",l:"中級",jp:"率直に申し上げますと",y:"そっちょくにもうしあげますと",vi:"Nói thẳng thì…",ex:"率直に申し上げますと、現案には反対です。"},
  // 依頼・催促
  {c:"request",l:"中級",jp:"何卒よろしくお願い申し上げます",y:"なにとぞよろしくおねがいもうしあげます",vi:"Kính mong (rất trang trọng)",ex:"ご多忙のところ恐縮ですが、何卒よろしくお願い申し上げます。"},
  {c:"request",l:"上級",jp:"ご一考いただけますでしょうか",y:"ごいっこういただけますでしょうか",vi:"Xin cân nhắc giúp",ex:"こちらの案もご一考いただけますでしょうか。"},
  {c:"request",l:"中級",jp:"ご教示いただけますでしょうか",y:"ごきょうじいただけますでしょうか",vi:"Xin chỉ giáo/hướng dẫn giúp",ex:"手順をご教示いただけますでしょうか。"},
  {c:"request",l:"中級",jp:"ご対応いただけますと幸いです",y:"ごたいおういただけますとさいわいです",vi:"Mong được xử lý giúp",ex:"今週中にご対応いただけますと幸いです。"},
  {c:"request",l:"上級",jp:"お取り計らいのほどお願いいたします",y:"おとりはからいのほどおねがいいたします",vi:"Nhờ thu xếp/châm chước giúp",ex:"よろしくお取り計らいのほどお願いいたします。",n:"Rất trang trọng — hợp văn bản gửi khách/cấp trên."},
  // 断り・お詫び
  {c:"decline",l:"中級",jp:"あいにくですが",y:"あいにくですが",vi:"Đáng tiếc là…",ex:"あいにくですが、その日は対応が難しいです。"},
  {c:"decline",l:"中級",jp:"ご期待に添えず申し訳ございません",y:"ごきたいにそえずもうしわけございません",vi:"Xin lỗi vì không đáp ứng được kỳ vọng",ex:"ご期待に添えず申し訳ございません。"},
  {c:"decline",l:"中級",jp:"難しい状況です",y:"むずかしいじょうきょうです",vi:"Tình hình khó (từ chối mềm)",ex:"現状では難しい状況です。",n:"Cách nói \"không\" gián tiếp kiểu Nhật — đối phương hiểu là từ chối."},
  {c:"decline",l:"中級",jp:"お役に立てず恐縮です",y:"おやくにたてずきょうしゅくです",vi:"Áy náy vì không giúp được",ex:"お役に立てず恐縮です。"},
  // 転換・つなぎ
  {c:"transition",l:"中級",jp:"さて",y:"さて",vi:"Nào, giờ thì… (chuyển sang việc chính)",ex:"さて、本題に入ります。"},
  {c:"transition",l:"中級",jp:"本題に入りますと",y:"ほんだいにはいりますと",vi:"Vào vấn đề chính thì…",ex:"本題に入りますと、納期の件です。"},
  {c:"transition",l:"中級",jp:"一方で",y:"いっぽうで",vi:"Mặt khác",ex:"一方で、コストの懸念も残ります。"},
  {c:"transition",l:"中級",jp:"とはいえ",y:"とはいえ",vi:"Tuy vậy",ex:"とはいえ、納期は死守したいです。"},
  {c:"transition",l:"上級",jp:"そうした中で",y:"そうしたなかで",vi:"Trong bối cảnh đó",ex:"そうした中で、優先順位の見直しが必要です。"},
  // 強調
  {c:"emphasis",l:"中級",jp:"特に",y:"とくに",vi:"Đặc biệt",ex:"特に初期フェーズが重要です。"},
  {c:"emphasis",l:"中級",jp:"なかでも",y:"なかでも",vi:"Trong số đó, nổi bật là",ex:"なかでも、移行作業が鍵です。"},
  {c:"emphasis",l:"中級",jp:"改めて",y:"あらためて",vi:"Một lần nữa",ex:"改めて、ご協力をお願いします。"},
  // 業務慣用句
  {c:"jargon",l:"中級",jp:"すり合わせ",y:"すりあわせ",vi:"Khớp/đối chiếu cho thống nhất",ex:"事前に方針をすり合わせましょう。"},
  {c:"jargon",l:"中級",jp:"認識合わせ",y:"にんしきあわせ",vi:"Căn chỉnh cách hiểu giữa các bên",ex:"一度、認識合わせをさせてください。"},
  {c:"jargon",l:"中級",jp:"工数",y:"こうすう",vi:"Số công / man-hour",ex:"この対応は工数がかかります。",hv:"công số"},
  {c:"jargon",l:"中級",jp:"横展開",y:"よこてんかい",vi:"Nhân rộng sang chỗ khác",ex:"この施策を他部門に横展開します。",hv:"hoành triển khai"},
  {c:"jargon",l:"中級",jp:"全体感",y:"ぜんたいかん",vi:"Bức tranh tổng thể",ex:"まず全体感を共有します。",hv:"toàn thể cảm"},
  {c:"jargon",l:"中級",jp:"肌感",y:"はだかん",vi:"Cảm nhận trực giác (chưa số liệu)",ex:"肌感では半々くらいです。"},
  {c:"jargon",l:"上級",jp:"鶴の一声",y:"つるのひとこえ",vi:"\"Một lời của sếp lớn\" quyết định tất",ex:"社長の鶴の一声で決まりました。"},
  {c:"jargon",l:"中級",jp:"詰めが甘い",y:"つめがあまい",vi:"Chốt chưa kỹ, hớ hênh khâu cuối",ex:"計画の詰めが甘かったです。"},
  // コンサル語彙
  {c:"consult",l:"上級",jp:"抽象度",y:"ちゅうしょうど",vi:"Mức độ trừu tượng",ex:"抽象度を一段下げて話しましょう。",hv:"trừu tượng độ"},
  {c:"consult",l:"上級",jp:"構造化",y:"こうぞうか",vi:"Cấu trúc hóa",ex:"課題を構造化して整理します。",hv:"cấu tạo hóa"},
  {c:"consult",l:"上級",jp:"当たりをつける",y:"あたりをつける",vi:"Khoanh vùng/đoán sơ bộ trước",ex:"まず当たりをつけてから調べます。"},
  {c:"consult",l:"上級",jp:"目線を合わせる",y:"めせんをあわせる",vi:"Căn chỉnh góc nhìn giữa các bên",ex:"関係者と目線を合わせます。"},
  {c:"consult",l:"上級",jp:"論点を立てる",y:"ろんてんをたてる",vi:"Đặt ra luận điểm cần bàn",ex:"会議の論点を立てておきます。"},
  {c:"consult",l:"上級",jp:"仮説を置く",y:"かせつをおく",vi:"Đặt giả thuyết",ex:"まず仮説を置いて検証します。"},
  {c:"consult",l:"上級",jp:"トレードオフ",y:"トレードオフ",vi:"Đánh đổi (được cái này mất cái kia)",ex:"コストと速度はトレードオフです。"},
  {c:"consult",l:"上級",jp:"全体最適",y:"ぜんたいさいてき",vi:"Tối ưu tổng thể (vs cục bộ)",ex:"部分最適ではなく全体最適を目指します。",hv:"toàn thể tối thích"},
  // 四字熟語
  {c:"yoji",l:"上級",jp:"一石二鳥",y:"いっせきにちょう",vi:"Một mũi tên trúng hai đích",ex:"これは一石二鳥の施策です。",hv:"nhất thạch nhị điểu"},
  {c:"yoji",l:"上級",jp:"本末転倒",y:"ほんまつてんとう",vi:"Đảo lộn gốc-ngọn, lệch trọng tâm",ex:"手段が目的化しては本末転倒です。",hv:"bản mạt điên đảo"},
  {c:"yoji",l:"上級",jp:"一朝一夕",y:"いっちょういっせき",vi:"(Không thể) một sớm một chiều",ex:"一朝一夕には解決しません。",hv:"nhất triêu nhất tịch"},
  {c:"yoji",l:"上級",jp:"日進月歩",y:"にっしんげっぽ",vi:"Tiến bộ từng ngày",ex:"技術は日進月歩です。",hv:"nhật tiến nguyệt bộ"},
  {c:"yoji",l:"上級",jp:"切磋琢磨",y:"せっさたくま",vi:"Cùng nhau rèn giũa tiến bộ",ex:"チームで切磋琢磨します。",hv:"thiết tha trác ma"},
  {c:"yoji",l:"上級",jp:"暗中模索",y:"あんちゅうもさく",vi:"Mò mẫm trong bóng tối",ex:"当初は暗中模索の状態でした。",hv:"ám trung mô tác"},
  {c:"yoji",l:"上級",jp:"起死回生",y:"きしかいせい",vi:"Lật ngược thế cờ từ tuyệt vọng",ex:"起死回生の一手を打ちます。",hv:"khởi tử hồi sinh"},
  {c:"yoji",l:"上級",jp:"温故知新",y:"おんこちしん",vi:"Ôn cố tri tân",ex:"温故知新で過去事例を見直します。",hv:"ôn cố tri tân"},
  {c:"yoji",l:"上級",jp:"我田引水",y:"がでんいんすい",vi:"\"Dẫn nước vào ruộng mình\" — vụ lợi",ex:"我田引水な主張は避けたいです。",n:"Nghĩa tiêu cực — dùng để phê phán.",hv:"ngã điền dẫn thủy"},
  {c:"yoji",l:"上級",jp:"不退転",y:"ふたいてん",vi:"Không lùi bước, quyết tâm sắt đá",ex:"不退転の決意で臨みます。",n:"Nặng/văn vẻ — hợp bài phát biểu, không hợp standup.",hv:"bất thoái chuyển"},
  {c:"yoji",l:"上級",jp:"率先垂範",y:"そっせんすいはん",vi:"Làm gương đi đầu",ex:"リーダーが率先垂範します。",n:"Trang trọng.",hv:"suất tiên thùy phạm"},
  {c:"yoji",l:"上級",jp:"換骨奪胎",y:"かんこつだったい",vi:"Cải biên cái cũ thành cái mới",ex:"既存案を換骨奪胎して使います。",n:"Văn vẻ — dùng dè.",hv:"hoán cốt đoạt thai"},
  // ことわざ
  {c:"proverb",l:"上級",jp:"二兎を追う者は一兎をも得ず",y:"にとをおうものはいっとをもえず",vi:"Đuổi hai thỏ mất cả hai",ex:"二兎を追う者は一兎をも得ず、と言います。"},
  {c:"proverb",l:"上級",jp:"船頭多くして船山に上る",y:"せんどうおおくしてふねやまにのぼる",vi:"Lắm thầy thối ma",ex:"船頭多くして船山に上る、にならないよう体制を絞ります。"},
  {c:"proverb",l:"上級",jp:"背に腹は代えられぬ",y:"せにはらはかえられぬ",vi:"Cùng tắc biến, đành hy sinh cái nhỏ",ex:"背に腹は代えられず、今回は外注します。"},
  {c:"proverb",l:"上級",jp:"転ばぬ先の杖",y:"ころばぬさきのつえ",vi:"Phòng bệnh hơn chữa bệnh",ex:"転ばぬ先の杖でバックアップを取ります。"},
  {c:"proverb",l:"上級",jp:"善は急げ",y:"ぜんはいそげ",vi:"Việc tốt thì làm ngay",ex:"善は急げで、今日中に着手します。"},
  {c:"proverb",l:"上級",jp:"失敗は成功のもと",y:"しっぱいはせいこうのもと",vi:"Thất bại là mẹ thành công",ex:"失敗は成功のもと、次に活かしましょう。"},
  {c:"proverb",l:"上級",jp:"灯台下暗し",y:"とうだいもとくらし",vi:"Bỏ sót cái ngay trước mắt",ex:"灯台下暗しで、答えは手元にありました。"},
  {c:"proverb",l:"上級",jp:"出る杭は打たれる",y:"でるくいはうたれる",vi:"Cây cao gió lớn / xuất đầu lộ diện bị dập",ex:"出る杭は打たれる風潮があります。"},
  {c:"proverb",l:"上級",jp:"三人寄れば文殊の知恵",y:"さんにんよればもんじゅのちえ",vi:"Ba cây chụm lại nên hòn núi cao",ex:"三人寄れば文殊の知恵、皆で考えましょう。"},
  {c:"proverb",l:"上級",jp:"千里の道も一歩から",y:"せんりのみちもいっぽから",vi:"Vạn dặm bắt đầu từ bước chân",ex:"千里の道も一歩から、まず着手します。"},
  {c:"proverb",l:"上級",jp:"喉元過ぎれば熱さを忘れる",y:"のどもとすぎればあつさをわすれる",vi:"Qua cơn hoạn nạn quên thầy",ex:"喉元過ぎれば熱さを忘れる、で再発しがちです。"},
  {c:"proverb",l:"上級",jp:"急いては事を仕損じる",y:"せいてはことをしそんじる",vi:"Dục tốc bất đạt (vội thì hỏng)",ex:"急いては事を仕損じる、慎重にいきましょう。"},

  // ===== nhóm MỚI =====
  // 挨拶・書き出し
  {c:"greeting",l:"中級",jp:"平素より大変お世話になっております",y:"へいそよりたいへんおせわになっております",vi:"Luôn cảm ơn sự giúp đỡ (mở mail trang trọng)",ex:"平素より大変お世話になっております。"},
  {c:"greeting",l:"中級",jp:"いつもお世話になっております",y:"いつもおせわになっております",vi:"Luôn được anh/chị quan tâm (mở mail chuẩn)",ex:"いつもお世話になっております。"},
  {c:"greeting",l:"中級",jp:"ご無沙汰しております",y:"ごぶさたしております",vi:"Lâu rồi không liên lạc",ex:"ご無沙汰しております。お変わりございませんか。"},
  {c:"greeting",l:"中級",jp:"早速ですが",y:"さっそくですが",vi:"Xin vào việc luôn",ex:"早速ですが、本件についてご相談です。"},
  {c:"greeting",l:"中級",jp:"標記の件につきまして",y:"ひょうきのけんにつきまして",vi:"Về việc nêu ở tiêu đề",ex:"標記の件につきまして、ご連絡いたします。"},
  {c:"greeting",l:"中級",jp:"下記の通りご案内いたします",y:"かきのとおりごあんないいたします",vi:"Xin thông báo như dưới đây",ex:"下記の通りご案内いたします。"},
  {c:"greeting",l:"中級",jp:"お忙しいところ失礼いたします",y:"おいそがしいところしつれいいたします",vi:"Xin lỗi làm phiền lúc bận (mở đầu)",ex:"お忙しいところ失礼いたします。"},
  {c:"greeting",l:"中級",jp:"突然のご連絡失礼いたします",y:"とつぜんのごれんらくしつれいいたします",vi:"Xin lỗi vì liên hệ đột ngột (cold mail)",ex:"突然のご連絡失礼いたします。"},
  // 結び
  {c:"closing",l:"中級",jp:"引き続きよろしくお願いいたします",y:"ひきつづきよろしくおねがいいたします",vi:"Mong tiếp tục hợp tác",ex:"引き続きよろしくお願いいたします。"},
  {c:"closing",l:"中級",jp:"今後ともよろしくお願い申し上げます",y:"こんごともよろしくおねがいもうしあげます",vi:"Mong được giúp đỡ về sau",ex:"今後ともよろしくお願い申し上げます。"},
  {c:"closing",l:"中級",jp:"取り急ぎご報告まで",y:"とりいそぎごほうこくまで",vi:"Tạm thời xin báo cáo vắn tắt",ex:"取り急ぎご報告まで。"},
  {c:"closing",l:"中級",jp:"まずはご連絡まで",y:"まずはごれんらくまで",vi:"Trước tiên xin liên hệ vậy",ex:"まずはご連絡まで。"},
  {c:"closing",l:"中級",jp:"ご査収のほどよろしくお願いいたします",y:"ごさしゅうのほどよろしくおねがいいたします",vi:"Mong anh/chị kiểm nhận (kèm file)",ex:"資料を添付いたします。ご査収のほどよろしくお願いいたします。"},
  {c:"closing",l:"中級",jp:"ご検討のほどよろしくお願いいたします",y:"ごけんとうのほどよろしくおねがいいたします",vi:"Mong anh/chị cân nhắc",ex:"ご検討のほどよろしくお願いいたします。"},
  {c:"closing",l:"中級",jp:"ご不明な点がございましたらお知らせください",y:"ごふめいなてんがございましたらおしらせください",vi:"Có gì chưa rõ xin báo",ex:"ご不明な点がございましたらお知らせください。"},
  {c:"closing",l:"中級",jp:"お手隙の際にご確認ください",y:"おてすきのさいにごかくにんください",vi:"Khi nào rảnh xin kiểm tra giúp",ex:"お手隙の際にご確認ください。"},
  {c:"closing",l:"中級",jp:"何卒よろしくお願いいたします",y:"なにとぞよろしくおねがいいたします",vi:"Kính mong giúp đỡ (kết)",ex:"何卒よろしくお願いいたします。"},
  // 感謝・お礼
  {c:"gratitude",l:"中級",jp:"厚く御礼申し上げます",y:"あつくおんれいもうしあげます",vi:"Xin chân thành cảm tạ",ex:"日頃のご支援に厚く御礼申し上げます。"},
  {c:"gratitude",l:"中級",jp:"感謝申し上げます",y:"かんしゃもうしあげます",vi:"Xin cảm ơn (trang trọng)",ex:"ご尽力に感謝申し上げます。"},
  {c:"gratitude",l:"上級",jp:"痛み入ります",y:"いたみいります",vi:"Cảm kích quá (khiêm tốn)",ex:"お心遣い、痛み入ります。"},
  {c:"gratitude",l:"中級",jp:"おかげさまで",y:"おかげさまで",vi:"Nhờ ơn anh/chị",ex:"おかげさまで、無事に完了しました。"},
  {c:"gratitude",l:"中級",jp:"恐縮でございます",y:"きょうしゅくでございます",vi:"Ngại quá / cảm kích quá",ex:"お褒めいただき恐縮でございます。"},
  {c:"gratitude",l:"中級",jp:"お力添えに感謝いたします",y:"おちからぞえにかんしゃいたします",vi:"Cảm ơn sự hỗ trợ",ex:"多大なお力添えに感謝いたします。"},
  {c:"gratitude",l:"上級",jp:"賜り",y:"たまわり",vi:"Được ban cho (kính ngữ của \"nhận\")",ex:"ご高配を賜り、誠にありがとうございます。",n:"Dùng trong văn bản trang trọng/lời chào."},
  // 確認・合意
  {c:"confirm",l:"中級",jp:"承知いたしました",y:"しょうちいたしました",vi:"Tôi đã hiểu/đồng ý (chuẩn business)",ex:"承知いたしました。対応いたします。"},
  {c:"confirm",l:"中級",jp:"かしこまりました",y:"かしこまりました",vi:"Vâng, tôi rõ (lễ độ hơn, với khách)",ex:"かしこまりました。"},
  {c:"confirm",l:"中級",jp:"ご認識の通りです",y:"ごにんしきのとおりです",vi:"Đúng như anh/chị hiểu",ex:"はい、ご認識の通りです。"},
  {c:"confirm",l:"上級",jp:"相違ございません",y:"そういございません",vi:"Không có gì khác/sai lệch",ex:"内容に相違ございません。",hv:"tương vi"},
  {c:"confirm",l:"上級",jp:"異存ございません",y:"いぞんございません",vi:"Tôi không phản đối",ex:"その方針で異存ございません。",hv:"dị tồn"},
  {c:"confirm",l:"中級",jp:"問題ございません",y:"もんだいございません",vi:"Không vấn đề gì",ex:"進め方に問題ございません。"},
  {c:"confirm",l:"中級",jp:"念のため確認させてください",y:"ねんのためかくにんさせてください",vi:"Cho tôi xác nhận lại cho chắc",ex:"念のため確認させてください。"},
  {c:"confirm",l:"上級",jp:"認識に齟齬がないか確認させてください",y:"にんしきにそごがないかかくにんさせてください",vi:"Xin xác nhận hai bên hiểu giống nhau",ex:"認識に齟齬がないか確認させてください。"},
  {c:"confirm",l:"中級",jp:"行き違いがあったようです",y:"いきちがいがあったようです",vi:"Hình như có nhầm lẫn/lệch thông tin",ex:"認識に行き違いがあったようです。"},
  // 報告・状況
  {c:"report",l:"中級",jp:"現状をご報告いたします",y:"げんじょうをごほうこくいたします",vi:"Xin báo cáo tình hình hiện tại",ex:"まず現状をご報告いたします。"},
  {c:"report",l:"中級",jp:"〜の見込みです",y:"〜のみこみです",vi:"Dự kiến / khả năng là…",ex:"今月末に完了の見込みです。"},
  {c:"report",l:"上級",jp:"〜の運びとなりました",y:"〜のはこびとなりました",vi:"Đã đi đến (kết quả)… (trang trọng)",ex:"契約締結の運びとなりました。"},
  {c:"report",l:"中級",jp:"目処が立ちました",y:"めどがたちました",vi:"Đã thấy hướng/triển vọng",ex:"解決の目処が立ちました。"},
  {c:"report",l:"上級",jp:"鋭意対応中です",y:"えいいたいおうちゅうです",vi:"Đang nỗ lực xử lý",ex:"現在、鋭意対応中です。"},
  {c:"report",l:"上級",jp:"善処いたします",y:"ぜんしょいたします",vi:"Sẽ xử lý ổn thỏa",ex:"ご指摘の点は善処いたします。",n:"Đôi khi bị hiểu là \"hứa cho qua\" — mơ hồ, dùng cẩn thận.",hv:"thiện xử"},
  {c:"report",l:"中級",jp:"滞りなく進んでおります",y:"とどこおりなくすすんでおります",vi:"Đang tiến triển suôn sẻ",ex:"作業は滞りなく進んでおります。"},
  {c:"report",l:"中級",jp:"遅れが生じております",y:"おくれがしょうじております",vi:"Đang phát sinh chậm trễ",ex:"一部、遅れが生じております。"},
  {c:"report",l:"中級",jp:"巻き返しを図ります",y:"まきかえしをはかります",vi:"Sẽ gỡ lại / lấy lại tiến độ",ex:"来週で巻き返しを図ります。"},
  // 会議進行・相槌
  {c:"facilitation",l:"中級",jp:"おっしゃる通りです",y:"おっしゃるとおりです",vi:"Đúng như anh/chị nói",ex:"おっしゃる通りです。"},
  {c:"facilitation",l:"中級",jp:"確かに",y:"たしかに",vi:"Đúng vậy / quả thật (đồng tình một phần)",ex:"確かに、その懸念はあります。"},
  {c:"facilitation",l:"中級",jp:"一点よろしいでしょうか",y:"いってんよろしいでしょうか",vi:"Cho tôi hỏi/nói một điểm được không",ex:"一点よろしいでしょうか。"},
  {c:"facilitation",l:"中級",jp:"補足させてください",y:"ほそくさせてください",vi:"Cho tôi bổ sung",ex:"補足させてください。"},
  {c:"facilitation",l:"中級",jp:"議論を戻しますと",y:"ぎろんをもどしますと",vi:"Quay lại chủ đề chính",ex:"議論を戻しますと、納期の話でした。"},
  {c:"facilitation",l:"上級",jp:"論点がずれているかもしれません",y:"ろんてんがずれているかもしれません",vi:"Có lẽ đang lệch trọng tâm",ex:"少し論点がずれているかもしれません。"},
  {c:"facilitation",l:"中級",jp:"時間の関係上",y:"じかんのかんけいじょう",vi:"Vì lý do thời gian",ex:"時間の関係上、次に進みます。"},
  {c:"facilitation",l:"中級",jp:"一旦持ち帰って",y:"いったんもちかえって",vi:"Tạm mang về (rồi quyết sau)",ex:"この点は一旦持ち帰って検討します。"},
  {c:"facilitation",l:"中級",jp:"巻きでお願いします",y:"まきでおねがいします",vi:"Xin đẩy nhanh tiến độ (nội bộ)",ex:"時間が押しているので巻きでお願いします。",n:"Rất casual — chỉ dùng nội bộ."},
  // 敬語語彙
  {c:"keigo",l:"中級",jp:"拝見します",y:"はいけんします",vi:"Xem (khiêm nhường của 見る)",ex:"資料を拝見します。",hv:"bái kiến"},
  {c:"keigo",l:"中級",jp:"拝読しました",y:"はいどくしました",vi:"Đã đọc (khiêm nhường)",ex:"メール、拝読しました。",hv:"bái độc"},
  {c:"keigo",l:"上級",jp:"拝聴します",y:"はいちょうします",vi:"Nghe (khiêm nhường)",ex:"ご説明を拝聴します。",hv:"bái thính"},
  {c:"keigo",l:"中級",jp:"伺います",y:"うかがいます",vi:"Hỏi / đến thăm / nghe (khiêm nhường)",ex:"後ほど詳細を伺います。"},
  {c:"keigo",l:"中級",jp:"頂戴します",y:"ちょうだいします",vi:"Nhận (khiêm nhường)",ex:"お名刺を頂戴します。",hv:"đỉnh đái"},
  {c:"keigo",l:"上級",jp:"申し伝えます",y:"もうしつたえます",vi:"Truyền đạt lại (cho người bên mình)",ex:"担当に申し伝えます。"},
  {c:"keigo",l:"中級",jp:"お目にかかる",y:"おめにかかる",vi:"Được gặp (khiêm nhường của 会う)",ex:"お目にかかれて光栄です。"},
  {c:"keigo",l:"上級",jp:"ご足労おかけします",y:"ごそくろうおかけします",vi:"Phiền anh/chị đi lại",ex:"ご足労おかけしますが、よろしくお願いします。"},
  {c:"keigo",l:"中級",jp:"ご査収ください",y:"ごさしゅうください",vi:"Xin kiểm nhận (file/tài liệu)",ex:"添付資料をご査収ください。"},
  {c:"keigo",l:"中級",jp:"存じます",y:"ぞんじます",vi:"Biết / nghĩ (khiêm nhường)",ex:"問題ないものと存じます。"},
  {c:"keigo",l:"上級",jp:"存じ上げております",y:"ぞんじあげております",vi:"Tôi có biết (về một người)",ex:"お名前は存じ上げております。"},
  {c:"keigo",l:"上級",jp:"いたしかねます",y:"いたしかねます",vi:"Khó lòng làm được (từ chối lịch sự)",ex:"その対応はいたしかねます。",n:"Cách nói \"không thể\" rất lễ độ."},
];
window.VOCAB_DATA.forEach((d,i)=>d.id="p"+i);
